# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sY6v-xjCHcI4L6XxQIxIy_rUr41Xm85_
"""

!pip install openpyxl

import openpyxl
import os

# Caminho do módulo openpyxl
print(os.path.dirname(openpyxl.__file__))

import os

# Nome da nova pasta
nome_da_pasta = "pasta_para_testes"

# Criar a pasta (caso ainda não exista)

caminho = "/datalab"  # Caminho completo no Colab
os.makedirs(caminho, exist_ok=True)

from openpyxl import Workbook

# Criar uma nova planilha
wb = Workbook()
ws = wb.active
ws.title = "Dados"

# Cabeçalhos
cabecalhos = ["Cidade", "Arrecadação", "Ano", "Clima"]
ws.append(cabecalhos)

# Preenchendo 20 linhas de dados fictícios
for i in range(1, 21):
    cidade = f"Cidade {i}"
    arrecadacao = 1000 * i
    ano = 2000 + (i % 10)
    clima = "Quente" if i % 2 == 0 else "Frio"
    ws.append([cidade, arrecadacao, ano, clima])

# Salvar o arquivo
wb.save("planilha_dados.xlsx")
print("Planilha criada com sucesso!")

from google.colab import files
files.download("planilha_dados.xlsx")

from openpyxl import Workbook

nova_aba = wb.create_sheet(title="Outra Planilha")
nova_aba.append(["Produto", "Preço"])

from openpyxl import load_workbook
import os

# Abrir a planilha existente
wb = load_workbook("planilha_dados.xlsx")
ws = wb.active  # Seleciona a aba ativa

# Adicionar novos cabeçalhos nas colunas E, F e G
ws["E1"] = "Regiões"
ws["F1"] = "Horário"
ws["G1"] = "Pluviosidade"

# (Opcional) Preencher com valores fictícios nas novas colunas
for row in range(2, 22):  # Da linha 2 até a 21 (20 linhas)
    ws[f"E{row}"] = f"Região {row-1}"
    ws[f"F{row}"] = f"{8 + (row-1)%12}:00"
    ws[f"G{row}"] = f"{(row-1) * 2} mm"

# Salvar com outro nome para preservar o original (opcional)
wb.save("planilha_dados_atualizada.xlsx")
print("Novas colunas adicionadas com sucesso!")

!pip install pymupdf openpyxl

import fitz  # PyMuPDF
import re
from openpyxl import Workbook

# Abrir o PDF
caminho_pdf = "/Conta 3 IRMAOS - Mar.pdf"  # Altere o caminho se necessário
doc = fitz.open(caminho_pdf)

# Expressões para encontrar os valores
padrao_uc = r"UC\s*[:\-]?\s*(\d+)"
padrao_compensacao = r"compensação\s*[:\-]?\s*([\d,\.]+)"
padrao_consumo = r"consumo\s*[:\-]?\s*([\d,\.]+)"
padrao_saldo = r"saldo\s*[:\-]?\s*([\d,\.\-]+)"

# Lista para armazenar os dados
dados_extraidos = []

# Extrair texto de cada página
for pagina in doc:
    texto = pagina.get_text()

    ucs = re.findall(padrao_uc, texto, re.IGNORECASE)
    compensacoes = re.findall(padrao_compensacao, texto, re.IGNORECASE)
    consumos = re.findall(padrao_consumo, texto, re.IGNORECASE)
    saldos = re.findall(padrao_saldo, texto, re.IGNORECASE)

    # Combinar os dados de forma segura
    for i in range(min(len(ucs), len(compensacoes), len(consumos), len(saldos))):
        dados_extraidos.append([
            compensacoes[i],
            consumos[i],
            saldos[i],
            ucs[i]
        ])

# Criar e salvar a planilha
wb = Workbook()
ws = wb.active
ws.title = "Dados"

# Cabeçalhos
ws.append(["Compensação", "Consumo", "Saldo", "UC"])

# Adicionar os dados extraídos
for linha in dados_extraidos:
    ws.append(linha)

# Salvar o arquivo
wb.save("dados_extraidos(2).xlsx")
print("Planilha criada com sucesso!")

import fitz  # PyMuPDF
import re
from openpyxl import Workbook

# Abrir o PDF
doc = fitz.open("/mnt/data/Conta 3 IRMAOS - Mar.pdf")

# Extrair texto
texto = ""
for pagina in doc:
    texto += pagina.get_text()

# Expressões
uc_match = re.search(r"\b(\d{10})\b", texto)
consumo_match = re.search(r"Consumo\s*-\s*TE.*?kWh\s*([\d.,]+)", texto)
compensacao_match = re.search(r"Energ Atv Inj.*?kWh\s*([\d.,]+)", texto)
saldo_match = re.search(r"Saldo em Energia.*?:.*?([\d.,]+)", texto)

# Valores
uc = uc_match.group(1) if uc_match else ""
consumo = consumo_match.group(1) if consumo_match else ""
compensacao = compensacao_match.group(1) if compensacao_match else ""
saldo = saldo_match.group(1) if saldo_match else ""

# Planilha
wb = Workbook()
ws = wb.active
ws.title = "Dados"
ws.append(["Compensação", "Consumo", "Saldo", "UC"])
ws.append([compensacao, consumo, saldo, uc])

# 🔽 Corrigido aqui
wb.save("/mnt/data/dados_extraidos_final.xlsx")
print("✅ Planilha criada com sucesso!")

import fitz  # PyMuPDF
import re
from openpyxl import Workbook

# Caminho correto do arquivo PDF
caminho_pdf = "/mnt/data/Conta 3 IRMAOS - Mar.pdf"

# Abrir o PDF
doc = fitz.open(caminho_pdf)

# Extrair o texto completo
texto = ""
for pagina in doc:
    texto += pagina.get_text()

# Expressões específicas conforme o texto do PDF
padrao_uc = r"\b(\d{10})\b"
padrao_consumo = r"Consumo\s*-\s*TE\s*MAR/25.*?kWh\s*([\d.,]+)"
padrao_compensacao = r"Energ Atv Inj\. oUC mPT.*?kWh\s*([\d.,]+)"
padrao_saldo = r"Saldo em Energia.*?:.*?([\d.,]+)"

# Extrair os dados
uc_match = re.search(padrao_uc, texto)
consumo_match = re.search(padrao_consumo, texto, re.IGNORECASE)
compensacao_match = re.search(padrao_compensacao, texto, re.IGNORECASE)
saldo_match = re.search(padrao_saldo, texto, re.IGNORECASE)

# Valores extraídos
uc = uc_match.group(1) if uc_match else ""
consumo = consumo_match.group(1) if consumo_match else ""
compensacao = compensacao_match.group(1) if compensacao_match else ""
saldo = saldo_match.group(1) if saldo_match else ""

# Criar e salvar a planilha
wb = Workbook()
ws = wb.active
ws.title = "Dados"
ws.append(["Compensação", "Consumo", "Saldo", "UC"])
ws.append([compensacao, consumo, saldo, uc])
wb.save("/mnt/data/dados_extraidos_final(2).xlsx")

# Print final corrigido
print("Planilha criada com sucesso!")

import fitz  # PyMuPDF
import re
import os
from openpyxl import Workbook

# Caminho da pasta com os PDFs
pasta_pdfs = "/mnt/data"

# Criar planilha
wb = Workbook()
ws = wb.active
ws.title = "Dados"
ws.append(["Arquivo", "Compensação", "Consumo", "Saldo", "UC"])

# Expressões ajustadas com maior flexibilidade
padrao_uc = r"\b(\d{10})\b"
padrao_consumo = r"Consumo\s*-\s*TE\s*[A-Z]{3}/\d{2}.*?([\d.]+)"
padrao_compensacao = r"Energ\s+Atv\s+Inj\.\s+oUC\s+mPT\s*-\s*TUSD\s*[A-Z]{3}/\d{2}.*?([\d.]+)"
padrao_saldo = r"Saldo em Energia.*?:.*?([\d.,]+)"

# Processar todos os PDFs da pasta
for nome_arquivo in os.listdir(pasta_pdfs):
    if nome_arquivo.lower().endswith(".pdf"):
        caminho_pdf = os.path.join(pasta_pdfs, nome_arquivo)
        try:
            doc = fitz.open(caminho_pdf)
            texto = ""
            for pagina in doc:
                texto += pagina.get_text()

            # Aplicar regex
            uc = re.search(padrao_uc, texto)
            consumo = re.search(padrao_consumo, texto, re.IGNORECASE | re.DOTALL)
            compensacao = re.search(padrao_compensacao, texto, re.IGNORECASE | re.DOTALL)
            saldo = re.search(padrao_saldo, texto, re.IGNORECASE)

            # Extrair valores
            uc_val = uc.group(1) if uc else ""
            consumo_val = consumo.group(1) if consumo else ""
            compensacao_val = compensacao.group(1) if compensacao else ""
            saldo_val = saldo.group(1) if saldo else ""

            # Adicionar à planilha
            ws.append([nome_arquivo, compensacao_val, consumo_val, saldo_val, uc_val])

        except Exception as e:
            print(f"Erro ao processar {nome_arquivo}: {e}")

# Salvar planilha
caminho_saida = os.path.join(pasta_pdfs, "dados_extraidos_todos.xlsx")
wb.save(caminho_saida)
print("✔ Planilha final criada com sucesso!")